[project]

name = "dmvqc"
version = "0.1"
authors = [
  { name="Diego Useche" },
  { name="Sebastian Molina" }
]
description = "DMVQC"
readme = "README.md"

dependencies = [
    'cirq',
    'grpcio-status',     
    'ipykernel',      
    'qiskit ',        
    'tensorcircuit',   
    'tensorflow', 
    'numpy',  
    'scipy',         
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8

[options.packages.find]
where = src
