[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]

name = "dmvqc"
version = "0.1"
authors = [
  { name="Diego Useche" },
  { name="Sebastian Molina" }
]
description = "DMVQC"
readme = "README.md"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages]

[options]
packages = find:
package_dir =
    =src


